---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-scope-cluster-agent
  labels:
    name: weave-scope-cluster-agent
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: weave-scope-cluster-agent
  template:
    metadata:
      labels:
        name: weave-scope-cluster-agent
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - weave-scope-cluster-agent
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: scope-cluster-agent
          args:
            - '--mode=probe'
            - '--probe-only'
            - '--probe.kubernetes.role=cluster'
            - '--probe.http.listen=:4041'
            - '--probe.publish.interval=4500ms'
            - '--probe.spy.interval=2s'
            - '--weave=false'
            - '--probe.no-controls=true'
            - 'weave-scope-app.weave.svc.cluster.local:4040'
          command:
            - /home/weave/scope
          env: []
          image: APP_IMAGE_NAME:SET_BY_CI
          imagePullPolicy: Always
          ports:
            - containerPort: 4041
              protocol: TCP
          resources:
            limits:
              memory: 2000Mi
            requests:
              cpu: 25m
              memory: 80Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 7007
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      serviceAccount: weave-agent
