apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weave

commonLabels:
  app: weave-scope

resources:
- daemon-set.agent.yaml
- deployment.app.yaml
- deployment.cluster-agent.yaml
- pdb.yaml
- service.yaml
- service-account.yaml
