---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:weave-agent
  namespace: weave
  labels:
    app: weave-scope
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - weave-agent
  verbs:
  - use
