---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:weave-agent
  namespace: weave
  labels:
    app: weave-scope
subjects:
- kind: ServiceAccount
  name: weave-agent
  namespace: weave
roleRef:
  kind: Role
  name: psp:weave-agent
  apiGroup: rbac.authorization.k8s.io
